function kg_in_plane=B_matrix_in_plane(gauss_points_x,gauss_points_y,sweep_angle,b,cr,I,J,K,L,M,N,P,Q,R,S,weights_x,weights_y,t_1,h_1,h,theta,thickness_of_each_ply)
% gauss_points_x=[-1/sqrt(3) 1/sqrt(3)];
% gauss_points_y=[-1/sqrt(3) 1/sqrt(3)];
% weights_x=[1 1];
% weights_y=[1 1];
% sweep_angle=30;%degree
% b=10;
% l_1=1;
% c=1;
% h=1;
% h_1=1;
 pi=3.1416;
% t_1=1;
sweep_angle_in_radians=sweep_angle*pi/180;
% cr=5;
 tip_chord=cr-((b/2)*tan(sweep_angle_in_radians));
%Linear nodes per element
% I=3;
% J=3;
% K=3;
% L=3;
% M=3;
% N=3;
% P=3;
% Q=3;
% R=3;
% S=3;
% dof=(5);
% icon_IJ=Assignment_1_Anirudh_K_ME22MTECH14017_case_3_question_2(2);
% icon_KL=Assignment_1_Anirudh_K_ME22MTECH14017_case_3_question_2(2);
% icon_PQ=Assignment_1_Anirudh_K_ME22MTECH14017_case_3_question_2(2);
% icon_RS=Assignment_1_Anirudh_K_ME22MTECH14017_case_3_question_2(2);
coeff_of_z_lower=Lower_fitting_a_curve();
coeff_of_z_upper=Upper_fitting_a_curve();
number_of_nodes_I_J=((I*J));
number_of_nodes_K_L=((K*L));
number_of_nodes_M_N=((M*N));
number_of_nodes_P_Q=((P*Q));
number_of_nodes_R_S=((R*S));
%number_of_elements=number_of_nodes-1;
P_non_derive_I_J_x=zeros(1,I*J);
P_derive_I_J_x=zeros(1,I*J);
P_derive_K_L_x=zeros(1,K*L);
P_non_derive_K_L_x=zeros(1,K*L);
P_derive_M_N_x=zeros(1,M*N);
P_non_derive_M_N_x=zeros(1,M*N);
P_non_derive_P_Q_x=zeros(1,P*Q);
P_derive_P_Q_x=zeros(1,P*Q);
P_non_derive_R_S_x=zeros(1,R*S);
P_derive_R_S_x=zeros(1,R*S);
P_non_derive_I_J_y=zeros(1,I*J);
P_derive_I_J_y=zeros(1,I*J);
P_derive_K_L_y=zeros(1,K*L);
P_non_derive_K_L_y=zeros(1,K*L);
P_derive_M_N_y=zeros(1,M*N);
P_non_derive_M_N_y=zeros(1,M*N);
P_non_derive_P_Q_y=zeros(1,P*Q);
P_derive_P_Q_y=zeros(1,P*Q);
P_non_derive_R_S_y=zeros(1,R*S);
P_derive_R_S_y=zeros(1,R*S);
B=zeros(12,(I*J+P*Q+M*N+K*L+R*S));
%  theta=[0 90 90 0];
%  thickness_of_each_ply=0.01*ones(1,length(theta));
hope=zeros((I*J+P*Q+M*N+K*L+R*S),(I*J+P*Q+M*N+K*L+R*S));
spar_position_I_J=linspace(-1,1,I*J);
spar_position_K_L=linspace(-1,1,K*L);
spar_position_P_Q=linspace(-1,1,P*Q);
spar_position_R_S=linspace(-1,1,R*S);
%kg=zeros(((I*J)+(K*L)+(P*Q)+(R*S))*dof,((I*J)+(K*L)+(P*Q)+(R*S))*dof);
for i=1:I*J%*length(icon_KL(:,1))*length(icon_KL(1,:))*length(icon_PQ(:,1))*length(icon_PQ(1,:))*length(icon_RS(:,1))*length(icon_RS(1,:)))
%     n11_IJ=icon_IJ(i,1);
%     n22_IJ=icon_IJ(i,2);
%     n33_IJ=icon_IJ(i,3);
%     n44_IJ=icon_IJ(i,4);
%     %n55_IJ=icon_IJ(i,5);
%     n11_KL=icon_KL(i,1);
%     n22_KL=icon_KL(i,2);
%     n33_KL=icon_KL(i,3);
%     n44_KL=icon_KL(i,4);
%     %n55_KL=icon_KL(i,5);
%     n11_PQ=icon_PQ(i,1);
%     n22_PQ=icon_PQ(i,2);
%     n33_PQ=icon_PQ(i,3);
%     n44_PQ=icon_PQ(i,4);
%     %n55_PQ=icon_PQ(i,5);
%     n11_RS=icon_RS(i,1);
%     n22_RS=icon_RS(i,2);
%     n33_RS=icon_RS(i,3);
%     n44_RS=icon_RS(i,4);
    %n55_RS=icon_RS(i,5);
    for op=1:length(gauss_points_y)
        c_special=0.5*cr*(1-gauss_points_y(op))+0.5*tip_chord*(1+gauss_points_y(op));
    for j=1:length(gauss_points_x)
P_non_derive_I_J_x(1,1)=1;
P_non_derive_I_J_x(1,2)=((t_1/(c_special))*gauss_points_x(j)+spar_position_I_J(1));
P_derive_I_J_x(1,1)=0;
P_derive_I_J_x(1,2)=1;
P_non_derive_K_L_x(1,1)=1;
P_non_derive_K_L_x(1,2)=((t_1/c_special)*gauss_points_x(j)+spar_position_K_L(1));
P_derive_M_N_x(1,1)=0;
P_derive_M_N_x(1,2)=1;
P_non_derive_M_N_x(1,1)=1;
P_non_derive_M_N_x(1,2)=gauss_points_x(j);
P_derive_M_N_x(1,1)=0;
P_derive_M_N_x(1,2)=1;
P_non_derive_P_Q_x(1,1)=1;
P_non_derive_P_Q_x(1,2)=((t_1/c_special)*gauss_points_x(j)+spar_position_P_Q(1));
P_derive_P_Q_x(1,1)=0;
P_derive_P_Q_x(1,2)=1;
P_non_derive_R_S_x(1,1)=1;
P_non_derive_R_S_x(1,2)=((t_1/c_special)*gauss_points_x(j)+spar_position_R_S(1));
P_derive_R_S_x(1,1)=0;
P_derive_R_S_x(1,2)=1;
P_non_derive_I_J_y(1,1)=1;
P_non_derive_I_J_y(1,2)=((t_1/c_special)*gauss_points_y(op)+spar_position_I_J(1));
P_derive_I_J_y(1,1)=0;
P_derive_I_J_y(1,2)=1;
P_non_derive_K_L_y(1,1)=1;
P_non_derive_K_L_y(1,2)=((t_1/c_special)*gauss_points_y(op)+spar_position_K_L(1));
P_derive_M_N_y(1,1)=0;
P_derive_M_N_y(1,2)=1;
P_non_derive_M_N_y(1,1)=1;
P_non_derive_M_N_y(1,2)=gauss_points_y(op);
P_derive_M_N_y(1,1)=0;
P_derive_M_N_y(1,2)=1;
P_non_derive_P_Q_y(1,1)=1;
P_non_derive_P_Q_y(1,2)=((t_1/c_special)*gauss_points_y(op)+spar_position_P_Q(1));
P_derive_P_Q_y(1,1)=0;
P_derive_P_Q_y(1,2)=1;
P_non_derive_R_S_y(1,1)=1;
P_non_derive_R_S_y(1,2)=((t_1/c_special)*gauss_points_y(op)+spar_position_R_S(1));
P_derive_R_S_y(1,1)=0;
P_derive_R_S_y(1,2)=1;
        for k=3:number_of_nodes_I_J
           P_derive_I_J_x(1,k)=((((2*k+1)/(k+1))*((t_1/c_special)*gauss_points_x(j)+spar_position_I_J(1,k-1)))*P_derive_I_J_x(1,k-1)-(k/(k+1)*P_derive_I_J_x(1,k-2))); 
           P_non_derive_I_J_x(1,k)=((((2*k+1)/(k+1))*((t_1/c_special)*gauss_points_x(j)+spar_position_I_J(1,k-1)))*P_non_derive_I_J_x(1,k-1)-(k/(k+1)*P_non_derive_I_J_x(1,k-2))); 
        end
        for k=3:number_of_nodes_K_L
           P_derive_K_L_x(1,k)=((((2*k+1)/(k+1))*((t_1/c_special)*gauss_points_x(j)+spar_position_K_L(1,k-1)))*P_derive_K_L_x(1,k-1)-(k/(k+1)*P_derive_K_L_x(1,k-2))); 
           P_non_derive_K_L_x(1,k)=((((2*k+1)/(k+1))*((t_1/c_special)*gauss_points_x(j)+spar_position_K_L(1,k-1)))*P_non_derive_K_L_x(1,k-1)-(k/(k+1)*P_non_derive_K_L_x(1,k-2))); 
        end
%         for k=3:number_of_nodes_M_N
%            P_derive_M_N_x(1,k)=((((2*k+1)/(k+1))*gauss_points_x(j))*P_derive_M_N_x(1,k-1)-(k/(k+1)*P_derive_M_N_x(1,k-2))); 
%            P_non_derive_M_N_x(1,k)=((((2*k+1)/(k+1))*gauss_points_x(op))*P_non_derive_M_N_x(1,k-1)-(k/(k+1)*P_non_derive_M_N_x(1,k-2))); 
%         end
        for k=3:number_of_nodes_P_Q
           P_derive_P_Q_x(1,k)=((((2*k+1)/(k+1))*((t_1/c_special)*gauss_points_x(j)+spar_position_P_Q(1,k-1)))*P_derive_P_Q_x(1,k-1)-(k/(k+1)*P_derive_P_Q_x(1,k-2))); 
           P_non_derive_P_Q_x(1,k)=((((2*k+1)/(k+1))*((t_1/c_special)*gauss_points_x(j)+spar_position_P_Q(1,k-1)))*P_non_derive_P_Q_x(1,k-1)-(k/(k+1)*P_non_derive_P_Q_x(1,k-2))); 
        end
        for k=3:number_of_nodes_R_S
           P_derive_R_S_x(1,k)=((((2*k+1)/(k+1))*(t_1/c_special)*(gauss_points_x(j)+spar_position_R_S(1,k-1)))*P_derive_R_S_x(1,k-1)-(k/(k+1)*P_derive_R_S_x(1,k-2))); 
           P_non_derive_R_S_x(1,k)=((((2*k+1)/(k+1))*((t_1/c_special)*gauss_points_x(j)+spar_position_R_S(1,k-1)))*P_non_derive_R_S_x(1,k-1)-(k/(k+1)*P_non_derive_R_S_x(1,k-2))); 
        end
        for k=3:number_of_nodes_I_J
           P_derive_I_J_y(1,k)=((((2*k+1)/(k+1))*((t_1/c_special)*gauss_points_y(op)+spar_position_I_J(1,k-1)))*P_derive_I_J_y(1,k-1)-(k/(k+1)*P_derive_I_J_y(1,k-2))); 
           P_non_derive_I_J_y(1,k)=((((2*k+1)/(k+1))*((t_1/c_special)*gauss_points_y(op)+spar_position_I_J(1,k-1)))*P_non_derive_I_J_y(1,k-1)-(k/(k+1)*P_non_derive_I_J_y(1,k-2))); 
        end
        for k=3:number_of_nodes_K_L
           P_derive_K_L_y(1,k)=((((2*k+1)/(k+1))*((t_1/c_special)*gauss_points_y(op)+spar_position_K_L(1,k-1)))*P_derive_K_L_x(1,k-1)-(k/(k+1)*P_derive_K_L_x(1,k-2))); 
           P_non_derive_K_L_y(1,k)=((((2*k+1)/(k+1))*((t_1/c_special)*gauss_points_y(op)+spar_position_K_L(1,k-1)))*P_non_derive_K_L_y(1,k-1)-(k/(k+1)*P_non_derive_K_L_y(1,k-2))); 
        end
%         for k=3:number_of_nodes_M_N
%            P_derive_M_N_y(1,k)=((((2*k+1)/(k+1))*gauss_points_y(j))*P_derive_M_N_y(1,k-1)-(k/(k+1)*P_derive_M_N_y(1,k-2))); 
%            P_non_derive_M_N_y(1,k)=((((2*k+1)/(k+1))*gauss_points_y(op))*P_non_derive_M_N_y(1,k-1)-(k/(k+1)*P_non_derive_M_N_y(1,k-2))); 
%         end
        for k=3:number_of_nodes_P_Q
           P_derive_P_Q_y(1,k)=((((2*k+1)/(k+1))*((t_1/c_special)*gauss_points_y(op)+spar_position_P_Q(1,k-1)))*P_derive_P_Q_y(1,k-1)-(k/(k+1)*P_derive_P_Q_y(1,k-2))); 
           P_non_derive_P_Q_y(1,k)=((((2*k+1)/(k+1))*((t_1/c_special)*gauss_points_y(op)+spar_position_P_Q(1,k-1)))*P_non_derive_P_Q_y(1,k-1)-(k/(k+1)*P_non_derive_P_Q_y(1,k-2))); 
        end
        for k=3:number_of_nodes_R_S
           P_derive_R_S_y(1,k)=((((2*k+1)/(k+1))*((t_1/c_special)*gauss_points_y(op)+spar_position_R_S(1,k-1)))*P_derive_R_S_y(1,k-1)-(k/(k+1)*P_derive_R_S_y(1,k-2))); 
           P_non_derive_R_S_y(1,k)=((((2*k+1)/(k+1))*((t_1/c_special)*gauss_points_y(op)+spar_position_R_S(1,k-1)))*P_non_derive_R_S_y(1,k-1)-(k/(k+1)*P_non_derive_R_S_y(1,k-2))); 
        end
        [detJacobian,inverse]=coordinate_transformation_Jacobian(sweep_angle,cr,b,gauss_points_x,gauss_points_y);
        inverse_trans=inverse';
        final_IJ_x=P_derive_I_J_x.*P_non_derive_I_J_x;
        final_KL_x=P_derive_K_L_x.*P_non_derive_K_L_x;
       % final_MN_x=P_derive_M_N_x.*P_non_derive_M_N_x;
        final_PQ_x=P_derive_P_Q_x.*P_non_derive_P_Q_x;
        final_RS_x=P_derive_R_S_x.*P_non_derive_R_S_x;
        final_IJ_y=P_derive_I_J_y.*P_non_derive_I_J_y;
        final_KL_y=P_derive_K_L_y.*P_non_derive_K_L_y;
        %final_MN_y=P_derive_M_N_y.*P_non_derive_M_N_y;
        final_PQ_y=P_derive_P_Q_y.*P_non_derive_P_Q_y;
        final_RS_y=P_derive_R_S_y.*P_non_derive_R_S_y;
        boom=5;
        idk=1;
%         final_IJ=[final_IJ_x;final_IJ_y];
%         final_KL=[final_KL_x;final_KL_y];
%         final_MN=[final_MN_x;final_MN_y];
%         final_PQ=[final_PQ_x;final_PQ_y];
%         final_RS=[final_RS_x;final_RS_y];
        for pi=1:length(final_IJ_x)
            B(1:12,idk:boom)=B(1:12,idk:boom)+[final_IJ_x(1,pi) 0 0 0 0;final_IJ_y(1,pi) 0 0 0 0;0 final_KL_x(1,pi) 0 0 0;0 final_KL_y(1,pi) 0 0 0;0 0 0 0 0;0 0 0 0 0;0 0 0 final_PQ_x(1,pi) 0;0 0 0 final_PQ_y(1,pi) 0;0 0 0 0 final_RS_x(1,pi);0 0 0 0 final_RS_y(1,pi);0 0 0 0 0;0 0 0 0 0];
            idk=idk+5;
            boom=boom+5;
        end
        D=D_matrix_general_in_plane(sweep_angle,cr,b,theta,thickness_of_each_ply,gauss_points_x,gauss_points_y,coeff_of_z_lower,h_1,coeff_of_z_upper,h);%+D_matrix_upper_airfoil_in_plane(sweep_angle,cr,b,theta,thickness_of_each_ply,gauss_points_x,gauss_points_y,coeff_of_z_upper,h_1);
        hope=hope+(t_1/c_special)*B'*D*B*weights_x(j)*weights_y(op)*detJacobian;
    end
    end
%     iv_0=[5*n11_IJ-4 5*n11_IJ-3 5*n11_IJ-2 5*n11_IJ-1 5*n11_IJ 5*n22_IJ-4 5*n22_IJ-3 5*n22_IJ-2 5*n22_IJ-1 5*n22_IJ 5*n33_IJ-4 5*n33_IJ-3 5*n33_IJ-2 5*n33_IJ-1 5*n33_IJ 5*n44_IJ-4 5*n44_IJ-3 5*n44_IJ-2 5*n44_IJ-1 5*n44_IJ];
%     iv_1=[5*n11_KL-4 5*n11_KL-3 5*n11_KL-2 5*n11_KL-1 5*n11_KL 5*n22_KL-4 5*n22_KL-3 5*n22_KL-2 5*n22_KL-1 5*n22_KL 5*n33_KL-4 5*n33_KL-3 5*n33_KL-2 5*n33_KL-1 5*n33_KL 5*n44_KL-4 5*n44_KL-3 5*n44_KL-2 5*n44_KL-1 5*n44_KL];
%     iv_2=[5*n11_PQ-4 5*n11_PQ-3 5*n11_PQ-2 5*n11_PQ-1 5*n11_PQ 5*n22_PQ-4 5*n22_PQ-3 5*n22_PQ-2 5*n22_PQ-1 5*n22_PQ 5*n33_PQ-4 5*n33_PQ-3 5*n33_PQ-2 5*n33_PQ-1 5*n33_PQ 5*n44_PQ-4 5*n44_PQ-3 5*n44_PQ-2 5*n44_PQ-1 5*n44_PQ];
%     iv_3=[5*n11_RS-4 5*n11_RS-3 5*n11_RS-2 5*n11_RS-1 5*n11_RS 5*n22_RS-4 5*n22_RS-3 5*n22_RS-2 5*n22_RS-1 5*n22_RS 5*n33_RS-4 5*n33_RS-3 5*n33_RS-2 5*n33_RS-1 5*n33_RS 5*n44_RS-4 5*n44_RS-3 5*n44_RS-2 5*n44_RS-1 5*n44_RS];
%     iv=[iv_0 iv_1 iv_2 iv_3];
    %kg(iv,iv)=kg(iv,iv)+hope;
end
kg_in_plane=hope;
end