function Stiffness_rib_cap=FEM_Main_file_ribs_cap(gauss_points_in_x,gauss_points_in_y,gauss_points_trans_x,gauss_points_trans_y,weights_in_x,weights_in_y,weights_trans_x,weights_trans_y,sweep,b,cr,I,J,K,L,M,N,P,Q,R,S,l_1,h_2,h,theta,thickness_of_each_ply)
% gauss_points_in_x=[-1/sqrt(3) 1/sqrt(3)];
% gauss_points_trans_x=0;
% gauss_points_in_y=[-1/sqrt(3) 1/sqrt(3)];
% gauss_points_trans_y=0;
% weights_in_x=[1 1];
% weights_in_y=[1 1];
% weights_trans_x=2;
% weights_trans_y=2;
% sweep=30;%degree
% b=10;
% cr=5;
% I=4;
% J=4;
% K=4;
% L=4;
% M=4;
% N=4;
% P=4;
% Q=4;
% R=4;
% S=4;
% l_1=1;
% %c=1;
% h=1;
% h_2=1;
B_in_plane=B_matrix_in_plane_rib_cap(gauss_points_in_x,gauss_points_in_y,sweep,b,cr,I,J,K,L,M,N,P,Q,R,S,weights_in_x,weights_in_y,l_1,h,h_2,theta,thickness_of_each_ply);
B_trans_plane=B_matrix_trans_plane_rib_cap(gauss_points_trans_x,gauss_points_trans_y,sweep,b,cr,I,J,K,L,M,N,P,Q,R,S,weights_trans_x,weights_trans_y,l_1,h,h_2,theta,thickness_of_each_ply);
Stiffness_rib_cap=B_in_plane+B_trans_plane;
end