function K_artificial_global=Artificial_Stiffness(I,J,K,L,M,N,P,Q,R,S,sweep_angle,span_of_the_entire_wing,root_of_chord,gauss_points_x,gauss_points_y,gauss_points_trans_x,gauss_points_trans_y,weights_x,weights_y,weights_trans_x,weights_trans_y)
%   I=4;
%  J=4;
%  K=4;
%  L=4;
%   M=4;
%    N=4;
%   P=4;
%   Q=4;
%    R=4;
%    S=4;
%    sweep_angle=30;%degree
%   span_of_the_entire_wing=4;
%   root_of_chord=5;
  %tip_chord=root_of_chord-((span_of_the_entire_wing/2)*tan(sweep_angle_in_radians));
  % gauss_points_x=[-1/sqrt(3) 1/sqrt(3)];
%   gauss_points_y=[-1/sqrt(3) 1/sqrt(3)];
%   weights_x=[1 1];
%   weights_y=[1 1];
% gauss_points_trans_x=0;
% gauss_points_trans_y=0;
% weights_trans_x=2;
% weights_trans_y=2;
  dummy_1=zeros(I*J,I*J);
  dummy_2=zeros(K*L,K*L);
  dummy_3=zeros(M*N,M*N);
  dummy_4=zeros(P*Q,P*Q);
K_artificial_global_1=Artificial_stiffness_K_11(I,J,K,L,M,N,P,Q,R,S,sweep_angle,span_of_the_entire_wing,root_of_chord,gauss_points_x,gauss_points_y,gauss_points_trans_x,gauss_points_trans_y,weights_x,weights_y,weights_trans_x,weights_trans_y);
K_artificial_global_2=Artificial_stiffness_K_22(I,J,K,L,M,N,P,Q,R,S,sweep_angle,span_of_the_entire_wing,root_of_chord,gauss_points_x,gauss_points_y,weights_x,weights_y,gauss_points_trans_x,gauss_points_trans_y,weights_trans_x,weights_trans_y);
K_artificial_global_3=Artificial_stiffness_K_33(I,J,K,L,M,N,P,Q,R,S,sweep_angle,span_of_the_entire_wing,root_of_chord,gauss_points_x,gauss_points_y,gauss_points_trans_x,gauss_points_trans_y,weights_x,weights_y,weights_trans_x,weights_trans_y);
K_artificial_global_4=Artificial_stiffness_K_44(I,J,K,L,M,N,P,Q,R,S,sweep_angle,span_of_the_entire_wing,root_of_chord,gauss_points_x,gauss_points_y,gauss_points_trans_x,gauss_points_trans_y,weights_x,weights_y,weights_trans_x,weights_trans_y);
K_artificial_global_5=Artificial_stiffness_K_55(I,J,K,L,M,N,P,Q,R,S,sweep_angle,span_of_the_entire_wing,root_of_chord,gauss_points_x,gauss_points_y,gauss_points_trans_x,gauss_points_trans_y,weights_x,weights_y,weights_trans_x,weights_trans_y);
K_artificial_global=[K_artificial_global_1 dummy_1 dummy_2 dummy_3 dummy_4;dummy_1 K_artificial_global_2 dummy_2 dummy_3 dummy_4;dummy_1 dummy_2 K_artificial_global_3 dummy_3 dummy_4;dummy_1 dummy_2 dummy_3 K_artificial_global_4 dummy_4;dummy_1 dummy_2 dummy_3 dummy_4 K_artificial_global_5];
end